#!/usr/bin/env node

/**
 * Bring the whole system up with one command.
 *
 * The only thing standing between `docker compose up` and a working demonstration is the signing
 * key, and the key is the one thing that must not be in the repository: every mandate signed with a
 * publicly-known secret is a mandate anyone can forge, and a development default is a key that
 * reaches production the first time somebody forgets an environment variable.
 *
 * So it is generated here, once, into a file git will not take, and reused on every later run — so
 * that a second `pnpm demo` continues the same campaign rather than silently starting a new
 * authority the ledger cannot connect to the first.
 */

import { spawn } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ENV_FILE = join(ROOT, ".env.demo");

function secret() {
  if (existsSync(ENV_FILE)) {
    const found = /^KAIROS_MANDATE_SECRET=(.+)$/m.exec(readFileSync(ENV_FILE, "utf8"));
    if (found !== null && found[1].trim().length >= 32)
      return { value: found[1].trim(), fresh: false };
  }

  const value = randomBytes(32).toString("hex");
  writeFileSync(
    ENV_FILE,
    [
      "# Generated by `pnpm demo`. Gitignored, and regenerated if you delete it.",
      "#",
      "# This is a real HMAC signing key. Every mandate in the demo stack is sealed with it and",
      "# verified against it on every single admission, which is why it is generated per machine",
      "# rather than committed: a key in a public repository authorises anyone who reads it.",
      `KAIROS_MANDATE_SECRET=${value}`,
      "",
    ].join("\n"),
  );
  return { value, fresh: true };
}

const key = secret();
if (key.fresh) {
  process.stderr.write(`generated a signing key into .env.demo — it is gitignored, keep it\n`);
}

const args = process.argv.slice(2);
const compose = args.length > 0 ? args : ["up", "--build"];

process.stderr.write(`docker compose ${compose.join(" ")}\n\n`);

// Inherited stdio, so Ctrl-C reaches compose and brings the stack down the way it would have if it
// had been typed directly. Wrapping it in anything cleverer would break that.
const child = spawn("docker", ["compose", "--env-file", ".env.demo", ...compose], {
  cwd: ROOT,
  stdio: "inherit",
});

child.on("error", (error) => {
  process.stderr.write(
    `${error.message}\n\nDocker does not appear to be running. Start Docker Desktop, or run the\n` +
      "stack without it: `pnpm build`, then the four processes in apps/ with the environment\n" +
      "docker-compose.yml gives them.\n",
  );
  process.exitCode = 1;
});

child.on("exit", (code) => {
  process.exitCode = code ?? 0;
});
